INSERT INTO [dbo].[FODMAPIngredients] (Name) VALUES
	('Agave Syrup'),
	('Apple'),
	('Amarinth Flour'),
	('Barley'),
	('Buttermilk'),
	('Einkorn'),
	('Emmer'),
	('Fruit Concentrate'),
	('Garlic'),
	('Glucose-fructose syrup'),
	('Pear'),
	('Nashi Pear'),
	('Clingstone Peaches'),
	('Mango'),
	('Sugar Snap Peas'),
	('Watermelon'),
	('Tinned Fruit in Natural Juice'),
	('Honey'),
	('Fructose'),
	('High Fructose Corn Syrup'),
	('Fruit Juice'),
	('Milk'),
	('Ice Cream'),
	('Yogurt'),
	('Ricotta'),
	('Cottage Cheese'),
	('Artichokes'),
	('Asparagus'),
	('Beetroot'),
	('Brussels sprout'),
	('Broccoli'),
	('Cabbage'),
	('Fennel'),
	('Garlic Powder'),
	('Garlic Salt'),
	('Leeks'),
	('Okra'),
	('Onions'),
	('Peas'),
	('Shallots'),
	('Rye'),
	('Chickpeas'),
	('Lentils'),
	('Red Kidney Beans'),
	('Baked Beans'),
	('Custard Apple'),
	('White Peaches'),
	('Rambutan'),
	('Persimmon'),
	('Apricot'),
	('Cherries'),
	('Longon'),
	('Lychee'),
	('Nectarine'),
	('Peach'),
	('Plum'),
	('Prune'),
	('Avocado'),
	('Cauliflower'),
	('Mushroom'),
	('Snow Pea'),
	('Milk Curds'),
	('Onion Salt'),
	('Onion Powder'),
	('Dried Fruit'),
	('Fruit Juice'),
	('Gram Flour'),
	('Inulin'),
	('Isoglucose'),
	('Isolated Fructose'),
	('Lentil Flour'),
	('Lupin'),
	('Sour Cream'),
	('Spelt'),
	('Fructans'),
	('Lactose'),
	('Apple Juice'),
	('Custard'),
	('Sweetened condensed milk'),
	('Cashews'),
	('Pistacios'),
	('Figs'),
	('Blackberries'),
	('Spring Onions'),
	('Split Peas'),
	('Green Peas'),
	('Falafel'),
	('Sausage'),
	('Salami')
GO

INSERT INTO [dbo].[FODMAPIngredients] (Name, Aliases) VALUES
	('Chickory Root', 'Chickory Extract'),
	('Khorasan Flour', 'Kamut'),
	('Chickpea Flour', 'Besan'),
	('Sorbitol','E420'),
	('Mannitol', 'E410'),
	('Xylitol','E967'),
	('Maltitol','E965'),
	('Isomalt','E953'),
	('Erythritol', 'E968'),
	('Fructooligosaccharides', 'FOS'),
	('Wheat', 'Gluten')
GO
